import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";

import { discoverAgent } from "#discover/discover-agent.js";
import { discoverFlatModuleSource, readSortedDirectoryEntries } from "#discover/grammar.js";
import { createDiskProjectSource } from "#discover/project-source.js";
import { SUPPORTED_AUTHORED_MODULE_FILE_EXTENSIONS } from "#discover/filesystem.js";

/**
 * Resolved build inputs for an extension package (a `package.json` declaring
 * `eve.extension`).
 */
export interface ExtensionBuildConfig {
  /** Absolute path to the agent-shaped source root (`eve.extension`). */
  readonly sourceRoot: string;
  /** Package name from `package.json`. */
  readonly packageName: string;
  /** Short name a consumer mounts by (`@acme/crm` → `crm`). */
  readonly shortName: string;
}

/**
 * Reads `package.json#eve.extension` from a project root, returning the
 * extension build inputs or `null` when the package is a regular agent app.
 */
export async function tryReadExtensionBuildConfig(
  rootDir: string,
): Promise<ExtensionBuildConfig | null> {
  const appRoot = resolve(rootDir);
  let pkg: { name?: unknown; eve?: { extension?: unknown } };
  try {
    pkg = JSON.parse(await readFile(join(appRoot, "package.json"), "utf8")) as typeof pkg;
  } catch {
    return null;
  }

  const extensionRoot = pkg.eve?.extension;
  if (typeof extensionRoot !== "string" || extensionRoot.length === 0) {
    return null;
  }

  const packageName = typeof pkg.name === "string" && pkg.name.length > 0 ? pkg.name : "extension";
  return {
    sourceRoot: resolve(appRoot, extensionRoot),
    packageName,
    shortName: packageName.slice(packageName.lastIndexOf("/") + 1),
  };
}

/**
 * Builds an extension package: emits `dist/index.mjs` (the mount factory,
 * re-exporting the extension's config handle as `default` and its short name)
 * and `dist/tools/index.mjs` (named tool re-exports for consumer overrides).
 * Re-exports point at the authored source so the consumer's compiled tools and
 * the mount share one config-handle instance.
 */
export async function buildExtensionPackage(
  rootDir: string,
  config: ExtensionBuildConfig,
): Promise<string> {
  const appRoot = resolve(rootDir);
  const source = createDiskProjectSource();

  const { diagnostics, manifest } = await discoverAgent({
    agentRoot: config.sourceRoot,
    appRoot,
    source,
    role: "extension",
  });
  const errors = diagnostics.filter((diagnostic) => diagnostic.severity === "error");
  if (errors.length > 0) {
    throw new Error(
      `Cannot build extension "${config.packageName}":\n${errors
        .map((diagnostic) => `  - ${diagnostic.message}`)
        .join("\n")}`,
    );
  }

  const rootEntries = await readSortedDirectoryEntries(source, config.sourceRoot);
  const configModule = discoverFlatModuleSource({
    rootEntries,
    rootPath: config.sourceRoot,
    slotName: "config",
  }).module;

  const outDir = join(appRoot, "dist");
  await mkdir(join(outDir, "tools"), { recursive: true });

  const specifierFrom = (fromDir: string, logicalPath: string): string => {
    const rel = relative(fromDir, join(config.sourceRoot, logicalPath)).replaceAll("\\", "/");
    return rel.startsWith(".") ? rel : `./${rel}`;
  };

  const indexLines = ["// Generated by eve. Do not edit by hand.", ""];
  if (configModule !== undefined) {
    const specifier = specifierFrom(outDir, configModule.logicalPath);
    indexLines.push(`export { default } from ${JSON.stringify(specifier)};`);
    indexLines.push(`export { default as ${config.shortName} } from ${JSON.stringify(specifier)};`);
  } else {
    indexLines.push("const mount = () => ({});");
    indexLines.push("export default mount;");
    indexLines.push(`export { mount as ${config.shortName} };`);
  }
  await writeFile(join(outDir, "index.mjs"), `${indexLines.join("\n")}\n`, "utf8");

  const toolLines = ["// Generated by eve. Do not edit by hand.", ""];
  for (const tool of manifest.tools) {
    const specifier = specifierFrom(join(outDir, "tools"), tool.logicalPath);
    toolLines.push(
      `export { default as ${toolExportName(tool.logicalPath)} } from ${JSON.stringify(specifier)};`,
    );
  }
  await writeFile(join(outDir, "tools", "index.mjs"), `${toolLines.join("\n")}\n`, "utf8");

  return outDir;
}

function toolExportName(logicalPath: string): string {
  let name = logicalPath;
  for (const extension of SUPPORTED_AUTHORED_MODULE_FILE_EXTENSIONS) {
    if (name.endsWith(extension)) {
      name = name.slice(0, name.length - extension.length);
      break;
    }
  }
  return name.replace(/^tools\//, "").replaceAll("/", "_");
}
